server:
  port : 8000
spring:
  cloud:
    gateway:
      routes:
      - id : userservice
        uri: http://localhost:8001/
        predicates:
          - Path=/user/**
      - id : carservice
        uri : http://localhost:8002/
        predicates:
          - Path=/car/**
      - id: bikeservice
        uri: http://localhost:8003/
        predicates:
          - Path=/bike/**
      globalcors:
        cors.configurations:
        '[/**]':
          allowedOrigins: "http://localhost:3000"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
